os:
  - linux
services:
  - docker
language: node_js
node_js:
  - '12.16.1'
cache:
  directories:
    - node
    - node_modules
    - $HOME/.gradle
env:
  global:
    - NODE_VERSION=12.16.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
before_install:
  - |
    if [[ $JHI_JDK = '8' ]]; then
      echo '*** Using OpenJDK 8'
    else
      echo '*** Using OpenJDK 11 by default'
      sudo add-apt-repository ppa:openjdk-r/ppa -y
      sudo apt-get update -q
      sudo apt-get install -y openjdk-11-jdk -y
      sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
      java -version
    fi
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - chmod +x gradlew
  - ./gradlew checkstyleNohttp
  - ./gradlew clean test integrationTest
  - ./gradlew npm_run_test -PnodeInstall --no-daemon
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then ./gradlew sonarqube --no-daemon -Dsonar.organization=muellners -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN; fi
  - ./gradlew bootJar -Pprod -x test
  - ./gradlew deployHeroku
notifications:
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
