version: '2'
services:
  bounties-app:
    image: bounties
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://bounties-mysql:3306/bounties?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JDBC_DATABASE_USERNAME=root
      - JDBC_DATABASE_PASSWORD=mysql
      - JDBC_DATABASE_URL=bounties-mysql
      - JDBC_DATABASE=bounties
      - JHIPSTER_CACHE_REDIS_SERVER=redis://bounties-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI= # TODO: GITHUB ISSUER
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID= # TODO: GITHUB ISSUER
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET= # TODO: GITHUB ISSUER
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - KAFKA_BOOTSTRAPSERVERS=bounties-kafka:9092
    ports:
      - 8080:8080
    depends_on:
      - bounties-mysql
      - bounties-kafka
      - bounties-redis
  bounties-mysql:
    extends:
      file: docker/mysql.yml
      service: bounties-mysql
  bounties-redis:
    extends:
      file: docker/redis.yml
      service: bounties-redis
  bounties-kafka:
    extends:
      file: docker/kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://bounties-kafka:9092
  zookeeper:
    extends:
      file: docker/kafka.yml
      service: zookeeper
